name = "cloudflare-vite-get-started"
compatibility_date = "2025-04-03"
main = "./src/index.ts"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1" 
new_sqlite_classes = ["MyDurableObject"] 